apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: mathtrail-infra

manifests:
  rawYaml:
    - dapr/namespace.yaml
    - dapr/components.yaml

deploy:
  kubectl:
    defaultNamespace: "{{.NAMESPACE}}"
  helm:
    releases:
      - name: dapr
        repo: "{{.CHARTS_REPO}}"
        remoteChart: dapr
        namespace: dapr-system
        createNamespace: true
        wait: true
