apiVersion: v1
kind: Secret
metadata:
  name: infra-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/MathTrail/infra
  username: git
  password: ${GITHUB_TOKEN}
