apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultConnection
metadata:
  name: vault-cluster-connection
  namespace: vault-config-operator
spec:
  address: http://vault.vault.svc.cluster.local:8200
  tls:
    skip_verify: true
