apiVersion: redhatcop.redhat.io/v1alpha1
kind: DatabaseSecretEngineRole
metadata:
  name: profile-api-role
  namespace: vault-config-operator
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  vaultAuthRef: vault-admin-auth
  path: database
  dBName: profile-postgres
  roleName: profile-api-role
  creationStatements:
    - >-
      CREATE ROLE "{{name}}" WITH LOGIN PASSWORD '{{password}}'
      VALID UNTIL '{{expiration}}';
      GRANT SELECT, INSERT, UPDATE, DELETE
      ON ALL TABLES IN SCHEMA public TO "{{name}}";
      GRANT USAGE ON SCHEMA public TO "{{name}}";
      GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO "{{name}}";
  revocationStatements:
    - >-
      REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM "{{name}}";
      DROP ROLE IF EXISTS "{{name}}";
  defaultTTL: 1h
  maxTTL: 24h
