---
- name: Bootstrap MathTrail Infrastructure
  hosts: localhost
  gather_facts: false

  pre_tasks:
    - name: Install kubernetes Python library
      ansible.builtin.command:
        cmd: "{{ ansible_playbook_python }} -m pip install kubernetes"
      register: _pip
      changed_when: "'Successfully installed' in _pip.stdout"

  roles:
    - role: argocd
    - role: infra_apps
